import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import Database from 'better-sqlite3';
import { randomUUID } from 'crypto';
dotenv.config();
const app=express(), db=new Database('motherlink.db');
app.use(cors()); app.use(express.json({limit:'1mb'}));
db.exec(`CREATE TABLE IF NOT EXISTS profile(id INTEGER PRIMARY KEY CHECK(id=1),name TEXT NOT NULL,dueDate TEXT NOT NULL,language TEXT NOT NULL DEFAULT 'en',contactName TEXT,contactPhone TEXT,consent INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS symptoms(id TEXT PRIMARY KEY,date TEXT NOT NULL,week INTEGER NOT NULL,rawText TEXT NOT NULL,symptoms TEXT NOT NULL,risk TEXT NOT NULL,advice TEXT NOT NULL,notified INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS checkups(id TEXT PRIMARY KEY,title TEXT NOT NULL,dueDate TEXT NOT NULL,type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'upcoming');
CREATE TABLE IF NOT EXISTS insights(id TEXT PRIMARY KEY,date TEXT NOT NULL,week INTEGER NOT NULL,type TEXT NOT NULL,summary TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,role TEXT NOT NULL,content TEXT NOT NULL,createdAt TEXT NOT NULL);`);
const today=()=>new Date().toISOString().slice(0,10);
const week=(due)=>Math.max(1,Math.min(42,Math.floor((new Date()-new Date(new Date(due).getTime()-280*864e5))/(7*864e5))+1));
const addInsight=(w,type,summary)=>db.prepare('INSERT INTO insights VALUES(?,?,?,?,?)').run(randomUUID(),today(),w,type,summary);
function seed(){if(db.prepare('SELECT 1 FROM profile').get())return; const due=new Date(Date.now()+140*864e5).toISOString().slice(0,10); db.prepare('INSERT INTO profile VALUES(1,?,?,?,?,?,?)').run('Ananya',due,'en','Priya','9876543210',1); const w=week(due); [['First antenatal check-up',-7,'checkup'],['Blood pressure & urine check',7,'checkup'],['TT/Td vaccination',14,'vaccine'],['Growth scan',28,'checkup']].forEach(([t,d,type])=>{let x=new Date(Date.now()+d*864e5).toISOString().slice(0,10);db.prepare('INSERT INTO checkups VALUES(?,?,?,?,?)').run(randomUUID(),t,x,type,'upcoming')}); addInsight(w,'weekly','Your body is doing important work. Eat regular balanced meals, hydrate, and keep your scheduled antenatal check-up.');} seed();
const patterns=[
 ['swelling',/(swelling|swollen|leg.*puff|kai kaal veekam|veekam)/i,'medium'],
 ['bleeding',/(bleed|blood|spotting|raththam|iratham)/i,'high'],
 ['severe headache',/(severe.*headache|bad.*headache|thalaivali romba|kadu[gm]ai.*thalai)/i,'high'],
 ['fever',/(fever|temperature|kaichal|jwar)/i,'medium'],
 ['abdominal pain',/(abdominal|stomach|belly|vayiru).*pain|(pain|vali).*(vayiru|stomach|abdomen)/i,'high'],
 ['reduced fetal movement',/(reduced.*movement|baby.*not.*mov|less.*kick|kuzhandhai.*asaiv|asaivu.*kura)/i,'high']
];
function analyse(text){const found=patterns.filter(x=>x[1].test(text)).map(x=>x[0]); const high=patterns.some(x=>x[2]==='high'&&x[1].test(text)); const risk=high?'high':found.length?'medium':'low'; const advice=risk==='high'?'Please contact your obstetrician or nearest emergency maternity service now. Heavy bleeding, severe pain, or markedly reduced movement need urgent assessment.':risk==='medium'?'Please rest, note when it started, and contact your maternity care team today if it persists, worsens, or you feel worried.':'No listed danger symptom was detected. Continue monitoring and mention this at your next check-up.'; return {found,risk,advice};}
function checks(profile){const rows=db.prepare('SELECT * FROM checkups ORDER BY dueDate').all(); return rows.map(c=>({...c, reminder:c.type==='vaccine'&&Math.round((new Date(c.dueDate)-new Date(today()))/864e5)===1}));}
app.get('/api/dashboard',(req,res)=>{const p=db.prepare('SELECT * FROM profile WHERE id=1').get();const w=week(p.dueDate); const s=db.prepare('SELECT * FROM symptoms ORDER BY date DESC LIMIT 5').all();res.json({profile:p,week:w,daysRemaining:Math.max(0,Math.ceil((new Date(p.dueDate)-new Date())/864e5)),checkups:checks(p),symptoms:s,insights:db.prepare('SELECT * FROM insights ORDER BY date DESC LIMIT 12').all()})});
app.put('/api/profile',(req,res)=>{let {name,dueDate,language,contactName,contactPhone,consent}=req.body;if(!name||!dueDate||new Date(dueDate).toString()==='Invalid Date'||new Date(dueDate)<=new Date('2000-01-01'))return res.status(400).json({error:'Enter a valid name and due date.'});db.prepare('UPDATE profile SET name=?,dueDate=?,language=?,contactName=?,contactPhone=?,consent=? WHERE id=1').run(name,dueDate,language||'en',contactName||'',contactPhone||'',consent?1:0);res.json({ok:true})});
app.post('/api/symptoms',(req,res)=>{const p=db.prepare('SELECT * FROM profile WHERE id=1').get(), text=String(req.body.text||'').trim();if(text.length<2||text.length>1000)return res.status(400).json({error:'Please describe your check-in in 2–1000 characters.'});const a=analyse(text),w=week(p.dueDate), notified=a.risk==='high'&&p.consent&&p.contactPhone?1:0;db.prepare('INSERT INTO symptoms VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),today(),w,text,JSON.stringify(a.found),a.risk,a.advice,notified);addInsight(w,'symptom',a.risk==='low'?'Check-in saved: no listed danger sign detected.':`${a.risk.toUpperCase()} risk check-in: ${a.found.join(', ')}.`);res.json({...a,notified,contact:notified?p.contactName:null})});
app.post('/api/checkups/:id/complete',(req,res)=>{const x=db.prepare('SELECT * FROM checkups WHERE id=?').get(req.params.id);if(!x)return res.status(404).json({error:'Check-up not found'});db.prepare("UPDATE checkups SET status='completed' WHERE id=?").run(x.id);res.json({ok:true})});
app.post('/api/chat',(req,res)=>{const q=String(req.body.message||'').trim();if(!q)return res.status(400).json({error:'Enter a question.'});const p=db.prepare('SELECT * FROM profile WHERE id=1').get(),w=week(p.dueDate);const caution=' I can provide general pregnancy education, not a diagnosis. If you have bleeding, severe headache, severe abdominal pain, fever, or reduced fetal movement, contact a clinician urgently.';let answer=/diet|food|eat/i.test(q)?'Focus on varied, well-cooked foods: vegetables, fruit, protein foods, whole grains, and fluids. Follow supplements prescribed by your clinician.':/movement|kick/i.test(q)?'Notice your baby’s usual movement pattern. If movement is clearly reduced, do not wait for the next check-up—contact your maternity care team now.':`You are about ${w} weeks pregnant based on the saved due date. Keep antenatal appointments, rest when needed, and ask your maternity team about concerns specific to you.`;answer+=caution;db.prepare('INSERT INTO messages VALUES(?,?,?,?)').run(randomUUID(),'user',q,new Date().toISOString());db.prepare('INSERT INTO messages VALUES(?,?,?,?)').run(randomUUID(),'assistant',answer,new Date().toISOString());res.json({answer})});
app.get('/api/doctor-summary',(req,res)=>{const p=db.prepare('SELECT * FROM profile WHERE id=1').get(),w=week(p.dueDate), s=db.prepare('SELECT * FROM symptoms ORDER BY date DESC LIMIT 10').all(); const list=s.map(x=>`${x.date}: ${JSON.parse(x.symptoms).join(', ')||'general check-in'} (${x.risk} risk)`).join('; ')||'No symptom logs yet.';res.json({summary:`Maternal check-in summary — ${p.name}, estimated ${w} weeks pregnant. Recent symptoms: ${list}. Upcoming care: ${db.prepare("SELECT title,dueDate FROM checkups WHERE status='upcoming' ORDER BY dueDate LIMIT 2").all().map(x=>x.title+' on '+x.dueDate).join(', ')||'none recorded'}. This is a discussion aid, not a clinical diagnosis.`})});
app.use((err,req,res,next)=>res.status(500).json({error:'Unexpected server error. Please try again.'}));app.listen(process.env.PORT||4000,()=>console.log('MotherLink API running'));
